version: "3.8"
services:
    cloudflared:
        container_name: cloudflared
        image: visibilityspots/cloudflared:arm64
        restart: unless-stopped
        networks:
            pihole_net:
                ipv4_address: 10.0.0.2

    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        restart: unless-stopped
        ports:
            - "80:80"
            - "53:53/udp"
            - "53:53/tcp"
        environment:
            - DNS1='10.0.0.2#5054'
            - DNS2=''
            - TZ=America/New_York
            - VIRTUAL_HOST=pi.hole
            - WEBPASSWORD=
            - TEMPERATUREUNIT=f
            - IPv6=false
            # - DNSMASQ_LISTENING=all
        volumes:
            - 'pihole:/etc/pihole'
            - 'dnsmasq:/etc/dnsmasq.d'
        networks:
            pihole_net:
                ipv4_address: 10.0.0.3
        dns:
            - 127.0.0.1
            - 1.1.1.1

networks:
    pihole_net:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/29

volumes:
    pihole:
    dnsmasq: