version: "3.8"
services:
    ddclient:
        container_name: ddclient
        image: lscr.io/linuxserver/ddclient:latest
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
            - HOMELOGIN
            - HOMEPASSWD
            - NOTESLOGIN
            - NOTESPASSWD
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /yggdrasil/config/ddclient/ddclient.conf:/config/ddclient.conf:ro
        network_mode: host

    caddy:
        container_name: caddy
        image: caddy:2-alpine
        restart: unless-stopped
        environment:
            - HOSTEMAIL
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - caddydata:/data
            - /yggdrasil/config/caddy:/etc/caddy:ro
        network_mode: host
        privileged: true

    joplindb:
        container_name: joplindb
        image: postgres:15
        volumes:
            - /yggdrasil/volumes/joplindb/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB=${POSTGRES_DATABASE}

    joplin:
        container_name: joplin
        image: etechonomy/joplin-server:latest
        platform: linux/arm64
        depends_on:
            - joplindb
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=${JOPLIN_APP_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD
            - POSTGRES_DATABASE
            - POSTGRES_USER
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=joplindb

    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        volumes:
            - /yggdrasil/volumes/uptime-kuma-data:/app/data
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "4040:3001"
        restart: always

volumes:
    caddydata: