version: "3.8"
services:
    ddclient:
        container_name: ddclient
        build: ./ddclient
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
            - HOMELOGIN=${HOMELOGIN}
            - HOMEPASSWD=${HOMEPASSWD}
        volumes:
            - /etc/localtime:/etc/localtime:ro
        network_mode: host

    caddy:
        container_name: caddy
        build: ./caddy
        restart: unless-stopped
        environment:
            - HOSTEMAIL=${HOSTEMAIL}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - caddydata:/data
            - caddyconfig:/config
        network_mode: host
        privileged: true

volumes:
    caddy:
    caddydata:
    caddyconfig: